let empanadasSabor=(prompt("de que sabor quiere su empanada"))
let saborGaseosa=(prompt("de que sabor quiere su gaseosa"))
let postre=(prompt("que postre desea"))
let cuantasEmpanadas=Number(prompt("cuantas empanadas desea"))
let cuantosPostres=Number(prompt("cuantos postres desea"))
let cuantasGaseosas=Number(prompt("cuantas gaseosas desea"))
